### PR TITLE
Layer Support for serverless colocate effective

### PR DESCRIPTION
**Pull request by dortega3000**

### CODE REVIEW

**Comment by dortega3000** [comment]
updated to support location of packaging of prebuilt artifacts

**Comment by dortega3000** [comment]
Can you please help mergin this change?

**Comment by dortega3000** [comment]
@aronim I would like to be a contributor to the plugin or even manage it if you dont have the time :)

**Comment by kevinsewell** [comment]
Hi dortega3000, 

I apologize for the silent treatment. As you correctly assumed, I have been too busy with my day job. Thank you so much for creating this pull request and for your offer to contribute to the project. I have added you as a collaborator.

Kind regards,
Kevin

**Pull request merged**
